version: "3.9"
services:

  chrome1:
    image: selenium/node-chrome:4.0.0-beta-4-20210608
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
    ports:
      - "9002:5900"

  chrome2:
    image: selenium/node-chrome:4.0.0-beta-4-20210608
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
    ports:
      - "9003:5900"

  chrome3:
    image: selenium/node-chrome:4.0.0-beta-4-20210608
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
    ports:
      - "9004:5900"

  chrome4:
    image: selenium/node-chrome:4.0.0-beta-4-20210608
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
    ports:
      - "9009:5900"

  edge1:
    image: selenium/node-edge:4.0.0-beta-4-20210608
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
    ports:
      - "9005:5900"

  edge2:
    image: selenium/node-edge:4.0.0-beta-4-20210608
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
    ports:
      - "9006:5900"

  edge3:
   image: selenium/node-edge:4.0.0-beta-4-20210608
   restart: always
   volumes:
      - /dev/shm:/dev/shm
   depends_on:
      - selenium-hub
   environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
   ports:
      - "9007:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-4-20210608
    restart: always
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 32
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
      JAVA_OPTS: -Xmx2048m
