version: "3.9"
services:

  edge1:
    image: selenium/node-edge:4.0.0-beta-4-20210608
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
    ports:
      - "9005:5900"

  edge2:
    image: selenium/node-edge:4.0.0-beta-4-20210608
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
    ports:
      - "9006:5900"

  edge3:
   image: selenium/node-edge:4.0.0-beta-4-20210608
   restart: always
   volumes:
      - /dev/shm:/dev/shm
   depends_on:
      - selenium-hub
   environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Xmx512m
   ports:
      - "9007:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-4-20210608
    restart: always
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 32
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
      JAVA_OPTS: -Xmx2048m

  codebase_edge:
    image: selenium-docker:v2
    depends_on:
      - edge1
      - edge2
      - edge3
    environment:
      - HUB_HOST=selenium-hub
      - BROWSER=${BROWSER:-edge}
      - MODULE=${MODULE:?Module option is missing!!!!}
      - JAVA_OPTS=-Xmx1024m
    volumes:
      - ./output_codebase_edge/test-output:/usr/share/selenium/test-output
      - ./output_codebase_edge/ScreenShots:/usr/share/selenium/ScreenShots
      - ./output_codebase_edge/TestRunLog:/usr/share/selenium/TestOutput/
